const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf-8'),
);
const output = `// Auto-generated by scripts/generate-version.js — do not edit\nexport const VERSION = '${pkg.version}';\n`;
fs.writeFileSync(
  path.join(__dirname, '..', 'src', 'lib', 'version.ts'),
  output,
);
